# Generated by Django 5.0 on 2023-12-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_todo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Done", "Done"),
                    ("In progress", "In progress"),
                    ("Not done", "Not done"),
                ],
                default="In progress",
                max_length=50,
            ),
        ),
    ]
